### ISSUE TITLE
I can't seem to get examples to start

### ISSUE THREAD

**Issue by alexhallam** [xliiv/fui#135]
I am using `cargo run --example feeders` and no program starts.

**Comment by xliiv** [comment]
Do you get any error? Should work, but I'll check it.

**Comment by alexhallam** [comment]
I did not get an error. I just got a new prompt. I am able to run the `cursive` programs though just not `fui`.

**Comment by alexhallam** [comment]
Perfect

**Comment by xliiv** [comment]
It should work now out of the box (on master of course).
