### ISSUE TITLE
All the images are broken links in the readme

### ISSUE THREAD

**Issue by Diggsey** [xliiv/fui#41]

**Comment by xliiv** [comment]
Thanks for the issue.
Could you provide a link or something more specific, because it works for me.

**Comment by Diggsey** [comment]
Here:

![image](https://user-images.githubusercontent.com/451321/37736665-63849f72-2d49-11e8-972d-fa72c62891c8.png)

And here:

![image](https://user-images.githubusercontent.com/451321/37736649-54caf4e0-2d49-11e8-95d0-b96942f847f0.png)

**Comment by Diggsey** [comment]
That's weird, looks like a CDN issue, I can see the images if I view from another region.
