### ISSUE TITLE
Default colors are suboptimal

### ISSUE THREAD

**Issue by matthiasbeyer** [xliiv/fui#42]
I tried the examples some days ago and I really liked what I saw.

Although, the default colors are a bit suboptimal: I was not able to understand that the color for the current selection is the same as for the input field.

Maybe those should change.

Or are these defaults provided by cursive? If yes, we should upstream this issue, of course.

**Comment by xliiv** [comment]
Second that.
I'm not sure why is that, but it's rahter `fui` fault`
Now it looks like this:
![image](https://user-images.githubusercontent.com/298994/37734944-eb1735e6-2d4c-11e8-9351-fcfe17400180.png)

But `cursive` renders it more like this:
![image](https://user-images.githubusercontent.com/298994/37735012-224972ea-2d4d-11e8-9696-0b25ee6c179f.png)

So of course it's way better.

**Comment by xliiv** [comment]
I made it "light black" with option of overriding it

**Comment by xliiv** [comment]
Thanks for this issue.
Feel free to create other if you find others :)
